Solar System - demo scence: src/curves.h File Reference
curves.h File Reference
#include <array>
#include <vector>
#include <glm/glm.hpp>
Functions
void renderCurve (mat4 M, const vector< vec3 > &control_points, unsigned int tesselation=100)
vector< vec3 > get_bezier_surface (const vector< array< vec3, 16 > > &control_set, int int_tesselation)
void get_curve (float time, const mat4 &M, const array< vec3, 4 > &control_points, glm::vec3 &pos, glm::vec3 &deriv)
void advance_in_curve (float translation_time, bool align, const mat4 &M, const vector< vec3 > &global_control_points)
Variables
const mat4 Mcr
const mat4 Mb
Function Documentation
advance_in_curve()
void advance_in_curve (float translation_time, bool align, const mat4 & M, const vector< vec3 > & global_control_points)
Definition at line 181 of file curves.cpp.
{
  // (x%N)/N
  float gt = fmodf ((float) glutGet (GLUT_ELAPSED_TIME), (float) (translation_time * 1000)) / (translation_time * 1000);
  vec3 pos;
  mat4 rot;
  align_global_pos_mat (gt, M, global_control_points, pos, rot);
  glTranslatef (pos.x, pos.y, pos.z);
  if (align)
    glMultMatrixf (value_ptr (rot));
}
References align_global_pos_mat().
Referenced by operations_render().
get_bezier_surface()
vector< vec3 > get_bezier_surface (const vector< array< vec3, 16 > > & control_set, int int_tesselation)
get_curve()
void get_curve (float time, const mat4 & M, const array< vec3, 4 > & control_points, glm::vec3 & pos, glm::vec3 & deriv)
renderCurve()
void renderCurve (mat4 M, const vector< vec3 > & control_points, unsigned int tesselation = 100)
Definition at line 156 of file curves.cpp.
{
  const auto step = 1.0 / tesselation;
  glm::vec3 pos;
  glm::vec3 deriv;
  glPushMatrix();
  glBegin (GL_LINE_STRIP);
  for (auto t = 0; t <= tesselation; ++t)
    {
      get_curve_global_point (t * step, M, control_points, pos, deriv);
      glVertex3f (pos.x, pos.y, pos.z);
    }
  glEnd ();
  //  for (auto p : control_points)
  //    {
  //      glPushMatrix ();
  //      glTranslatef (p.x, p.y, p.z);
  //      glutSolidSphere (.02, 10, 10);
  //      glPopMatrix ();
  //    }
    glPopMatrix();
}
References get_curve_global_point().
Referenced by operations_render().
Variable Documentation
Mb
const mat4 Mb
Definition at line 7 of file curves.h.
Mcr
const mat4 Mcr extern
Definition at line 8 of file curves.cpp.
Referenced by operations_render().