Solar System - demo scence: src/generator.cpp File Reference
generator.cpp File Reference
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <glm/glm.hpp>
#include <glm/gtx/string_cast.hpp>
#include <vector>
#include <string>
#include <sstream>
#include <fstream>
#include <tuple>
#include <iostream>
#include "curves.h"
Macros
#define _USE_MATH_DEFINES
Functions
void points_vertex (const float x, const float y, const float z, unsigned int *pos, float points[])
void points_write (const char *filename, const unsigned int nVertices, const float points[])
void model_plane_vertices (const float length, const unsigned int divisions, float *points)
unsigned int model_plane_nVertices (const unsigned int divisions)
void model_plane_write (const char *filepath, const float length, const unsigned int divisions)
void model_cube_vertices (const float length, const unsigned int divisions, float points[])
unsigned int model_cube_nVertices (const unsigned int divisions)
void model_cube_write (const char *filepath, const float length, const unsigned int divisions)
static void model_cone_vertex (const float r, const float height, const float theta, const float h, unsigned int *pos, float *points)
void model_cone_vertices (const float r, const float height, const unsigned int slices, const unsigned int stacks, float points[])
static unsigned int model_cone_nVertices (const unsigned int stacks, const unsigned int slices)
void model_cone_write (const char *filepath, const float radius, const float height, const unsigned int slices, const unsigned int stacks)
static void model_sphere_vertex (const float r, const float theta, const float phi, unsigned int *pos, float *points)
static void model_sphere_vertices (const float r, const unsigned int slices, const unsigned int stacks, float points[])
vector< array< vec3, 16 > > read_Bezier (const char *patch)
void model_bezier_write (int tesselation, const char *in_patch_file, const char *out_3d_file)
static unsigned int model_sphere_nVertices (const unsigned int slices, const unsigned int stacks)
void model_sphere_write (const char *filepath, float radius, unsigned int slices, unsigned int stacks)
int main (int argc, char *argv[])
Variables
const char * SPHERE = "sphere"
const char * CUBE = "box"
const char * CONE = "cone"
const char * PLANE = "plane"
const char * BEZIER = "bezier"
Macro Definition Documentation
_USE_MATH_DEFINES
#define _USE_MATH_DEFINES
Definition at line 1 of file generator.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 451 of file generator.cpp.
{
  if (argc < 4)
    {
      printf ("Not enough arguments");
    }
  else
    {
      const char *out_file_path = argv[argc - 1];
      const char *polygon = argv[1];
      if (!strcmp (PLANE, polygon))
        model_plane_write (out_file_path, strtof (argv[2], nullptr), strtoul (argv[3], nullptr, 10));
      if (!strcmp (CUBE, polygon))
        model_cube_write (out_file_path, atof (argv[2]), strtoul (argv[3], nullptr, 10));
      if (!strcmp (CONE, polygon))
        model_cone_write (out_file_path, atof (argv[2]), atof (argv[3]), atoi (argv[4]), atoi (argv[5]));
      if (!strcmp (SPHERE, polygon))
        model_sphere_write (out_file_path, atof (argv[2]), atoi (argv[3]), atoi (argv[4]));
      if (!strcmp (BEZIER, polygon))
        model_bezier_write (atoi (argv[2]), argv[3], out_file_path);
    }
  return 0;
}
References BEZIER, CONE, CUBE, model_bezier_write(), model_cone_write(), model_cube_write(), model_plane_write(), model_sphere_write(), PLANE, and SPHERE.
Variable Documentation
BEZIER
const char* BEZIER = "bezier"
Definition at line 26 of file generator.cpp.
Referenced by main().
CONE
const char* CONE = "cone"
Definition at line 24 of file generator.cpp.
Referenced by main().
CUBE
const char* CUBE = "box"
Definition at line 23 of file generator.cpp.
Referenced by main().
PLANE
const char* PLANE = "plane"
Definition at line 25 of file generator.cpp.
Referenced by main().
SPHERE
const char* SPHERE = "sphere"
Definition at line 22 of file generator.cpp.
Referenced by main().