Solar System - demo scence: Model
Model
Engine
Classes
struct model
Typedefs
typedef struct model * Model
Functions
Model allocModel (const char *path)
void renderModel (Model model, GLuint vbo_ix)
void renderAllModels ()
size_t readModelToBuffer (const char *path, float *p, unsigned int n)
Variables
static std::vector< Model > globalModels
static std::vector< float > globalOperations
static bool operations_hasBeenInitialized = false
Detailed Description
Typedef Documentation
Model
typedef struct model * Model
Function Documentation
allocModel()
Model allocModel (const char * path)
Definition at line 209 of file engine.cpp.
{
  FILE *fp = fopen (path, "r");
  if (!fp)
    {
      fprintf (stderr, "failed to open model: %s\n", path);
      exit (1);
    }
  unsigned int nVertices;
  fread (&nVertices, sizeof (unsigned int), 1, fp);
  float *modelBuf = (float *) malloc (3 * nVertices * sizeof (float));
  fread (modelBuf, 3 * sizeof (float), nVertices, fp);
  fclose (fp);
  Model model = (Model) malloc (sizeof (Model));
  if (model == NULL)
    {
      fprintf (stderr, "Failed loading model\n");
      exit (1);
    }
  model->nVertices = nVertices;
  model->vertices = modelBuf;
  return model;
}
References model::nVertices, and model::vertices.
Referenced by operations_render().
readModelToBuffer()
size_t readModelToBuffer (const char * path, float * p, unsigned int n)
Definition at line 260 of file engine.cpp.
{
  FILE *fp = fopen (path, "r");
  size_t r = fread (p, sizeof (float), n, fp);
  fclose (fp);
  return r;
}
renderAllModels()
void renderAllModels ()
Definition at line 252 of file engine.cpp.
{
  for (int i = 0; i < globalModels.size (); i++)
    {
      renderModel (globalModels[i], vbo_indices[i]);
    }
}
References globalModels, renderModel(), and vbo_indices().
renderModel()
void renderModel (Model model, GLuint vbo_ix)
Definition at line 238 of file engine.cpp.
{
  if (!model->nVertices % 3)
    {
      fprintf (stderr, "Number of coordinates is not divisible by 3");
      exit (1);
    }
  glBindBuffer (GL_ARRAY_BUFFER, vbo_ix);
  glVertexPointer (3, GL_FLOAT, 0, 0);
  glDrawArrays (GL_TRIANGLES, 0, model->nVertices);
  glBindBuffer (GL_ARRAY_BUFFER, 0); //unbind
}
References model::nVertices.
Referenced by operations_render(), and renderAllModels().
Variable Documentation
globalModels
std::vector<Model> globalModels static
Definition at line 205 of file engine.cpp.
Referenced by operations_render(), and renderAllModels().
globalOperations
std::vector<float> globalOperations static
Definition at line 206 of file engine.cpp.
Referenced by renderScene(), and xml_load_and_set_env().
operations_hasBeenInitialized
bool operations_hasBeenInitialized = false static
Definition at line 207 of file engine.cpp.