Solar System - demo scence: Models
Models
Operations
Functions
void operations_push_model (tinyxml2::XMLElement *model, std::vector< float > *operations)
void operations_push_models (tinyxml2::XMLElement *models, std::vector< float > *operations)
Detailed Description
Function Documentation
operations_push_model()
void operations_push_model (tinyxml2::XMLElement * model, std::vector< float > * operations)
Definition at line 143 of file parsing.cpp.
{
  unsigned int i = 0;
  const char *string = model->Attribute ("file");
  operations->push_back (LOAD_MODEL);
  do
    operations->push_back (string[i++]);
  while (string[i]);
  if (i <= 0)
    {
      fprintf (stderr, "filename is empty");
      exit (1);
    }
  //i--;
  operations->insert (operations->end () - i, (float) i);
}
References LOAD_MODEL.
Referenced by operations_push_models().
operations_push_models()
void operations_push_models (tinyxml2::XMLElement * models, std::vector< float > * operations)
Definition at line 165 of file parsing.cpp.
{
  tinyxml2::XMLElement *model = models->FirstChildElement ("model");
  do
    operations_push_model (model, operations);
  while ((model = model->NextSiblingElement ("model")));
}
References operations_push_model().
Referenced by operations_push_groups().