Solar System - demo scence: Transforms
Transforms
Operations
Functions
void operations_push_transform_attributes (tinyxml2::XMLElement *transform, std::vector< float > *operations)
void operations_push_extended_translate_attributes (tinyxml2::XMLElement *extended_translate, std::vector< float > *operations)
void operations_push_transformation (tinyxml2::XMLElement *transformation, std::vector< float > *operations)
void operations_push_transforms (tinyxml2::XMLElement *transforms, std::vector< float > *operations)
Detailed Description
Function Documentation
operations_push_extended_translate_attributes()
void operations_push_extended_translate_attributes (tinyxml2::XMLElement * extended_translate, std::vector< float > * operations)
Definition at line 64 of file parsing.cpp.
{
  if (!extended_translate)
    {
      fprintf (stderr, "Null transform\n");
      exit (1);
    }
  float time = extended_translate->FloatAttribute ("time");
  bool align = extended_translate->BoolAttribute ("align");
  int number_of_points = 0;
  operations->push_back ((float) time);
  operations->push_back ((float) align);
  operations->push_back (0);
  auto index_of_number_of_points = operations->size () - 1;
  for (auto child = extended_translate->FirstChildElement ("point"); child; child = child->NextSiblingElement ("point"))
    {
      number_of_points++;
      operations_push_transform_attributes (child, operations);
    }
    operations->at (index_of_number_of_points) = number_of_points;
}
References operations_push_transform_attributes().
Referenced by operations_push_transformation().
operations_push_transform_attributes()
void operations_push_transform_attributes (tinyxml2::XMLElement * transform, std::vector< float > * operations)
Definition at line 49 of file parsing.cpp.
{
  if (!transform)
    return;
  float angle = transform->FloatAttribute ("angle");
  if ((int) angle)
    operations->push_back (angle);
  operations->push_back (transform->FloatAttribute ("x"));
  operations->push_back (transform->FloatAttribute ("y"));
  operations->push_back (transform->FloatAttribute ("z"));
}
Referenced by operations_load_xml(), operations_push_extended_translate_attributes(), and operations_push_transformation().
operations_push_transformation()
void operations_push_transformation (tinyxml2::XMLElement * transformation, std::vector< float > * operations)
Definition at line 89 of file parsing.cpp.
{
  const char *transform_name = transformation->Value ();
  if (!strcmp ("translate", transform_name))
    {
      if (transformation->Attribute ("time") != NULL)
        {
          operations->push_back (EXTENDED_TRANSLATE);
          operations_push_extended_translate_attributes (transformation, operations);
        }
      else
        {
          operations->push_back (TRANSLATE);
          operations_push_transform_attributes (transformation, operations);
        }
    }
  else if (!strcmp ("rotate", transform_name))
    {
      if (transformation->Attribute ("time")) {
        operations->push_back (EXTENDED_ROTATE);
        float time = transformation->FloatAttribute ("time");
        operations->push_back (time);
        operations_push_transform_attributes (transformation, operations);
      }
      else {
        operations->push_back (ROTATE);
        operations_push_transform_attributes (transformation, operations);
      }
    }
  else if (!strcmp ("scale", transform_name)) {
    operations->push_back (SCALE);
    operations_push_transform_attributes (transformation, operations);
  }
  else
    {
      fprintf (stderr, "Unknown transform: \"%s\"", transform_name);
      exit (1);
    }
}
References EXTENDED_ROTATE, EXTENDED_TRANSLATE, operations_push_extended_translate_attributes(), operations_push_transform_attributes(), ROTATE, SCALE, and TRANSLATE.
Referenced by operations_push_transforms().
operations_push_transforms()
void operations_push_transforms (tinyxml2::XMLElement * transforms, std::vector< float > * operations)
Definition at line 130 of file parsing.cpp.
{
  tinyxml2::XMLElement *transform = transforms->FirstChildElement ();
  do
      operations_push_transformation(transform,operations);
  while ((transform = transform->NextSiblingElement ()));
}
References operations_push_transformation().
Referenced by operations_push_groups().