Solar System - demo scence: Cube
Cube
Generator » Model
Functions
void model_cube_vertices (const float length, const unsigned int divisions, float points[])
unsigned int model_cube_nVertices (const unsigned int divisions)
void model_cube_write (const char *filepath, const float length, const unsigned int divisions)
Detailed Description
Function Documentation
model_cube_nVertices()
unsigned int model_cube_nVertices (const unsigned int divisions)
Definition at line 180 of file generator.cpp.
{ return divisions * divisions * 36; }
Referenced by model_cube_write().
model_cube_vertices()
void model_cube_vertices (const float length, const unsigned int divisions, float points[])
Definition at line 109 of file generator.cpp.
{
  const float o = -length / 2.0f;
  const float d = length / (float) divisions;
  unsigned int pos = 0;
  for (unsigned int m = 1; m <= divisions; m++)
    {
      for (unsigned int n = 1; n <= divisions; n++)
        {
          float i = (float) m;
          float j = (float) n;
          // top
          points_vertex (o + d * (i - 1), -o, o + d * (j - 1), &pos, points); //P1
          points_vertex (o + d * (i - 1), -o, o + d * j, &pos, points); //P1'z
          points_vertex (o + d * i, -o, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (o + d * i, -o, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (o + d * (i - 1), -o, o + d * j, &pos, points); //P1'z
          points_vertex (o + d * i, -o, o + d * j, &pos, points); //P2
          // bottom
          points_vertex (o + d * (i - 1), o, o + d * j, &pos, points); //P1'z
          points_vertex (o + d * (i - 1), o, o + d * (j - 1), &pos, points); //P1
          points_vertex (o + d * i, o, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (o + d * (i - 1), o, o + d * j, &pos, points); //P1'z
          points_vertex (o + d * i, o, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (o + d * i, o, o + d * j, &pos, points); //P2
          // left
          points_vertex (o, o + d * (i - 1), o + d * (j - 1), &pos, points); //P1
          points_vertex (o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
          points_vertex (o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
          points_vertex (o, o + d * i, o + d * j, &pos, points); //P2
          // right
          points_vertex (-o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
          points_vertex (-o, o + d * (i - 1), o + d * (j - 1), &pos, points); //P1
          points_vertex (-o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (-o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
          points_vertex (-o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
          points_vertex (-o, o + d * i, o + d * j, &pos, points); //P2
          // front
          points_vertex (o + d * (i - 1), o + d * (j - 1), o, &pos, points); //P1
          points_vertex (o + d * (i - 1), o + d * j, o, &pos, points); //P1'z
          points_vertex (o + d * i, o + d * (j - 1), o, &pos, points); //P1'x
          points_vertex (o + d * i, o + d * (j - 1), o, &pos, points); //P1'x
          points_vertex (o + d * (i - 1), o + d * j, o, &pos, points); //P1'z
          points_vertex (o + d * i, o + d * j, o, &pos, points); //P2
          // back
          points_vertex (o + d * (i - 1), o + d * j, -o, &pos, points); //P1'z
          points_vertex (o + d * (i - 1), o + d * (j - 1), -o, &pos, points); //P1
          points_vertex (o + d * i, o + d * (j - 1), -o, &pos, points); //P1'x
          points_vertex (o + d * (i - 1), o + d * j, -o, &pos, points); //P1'z
          points_vertex (o + d * i, o + d * (j - 1), -o, &pos, points); //P1'x
          points_vertex (o + d * i, o + d * j, -o, &pos, points); //P2
        }
    }
}
References points_vertex().
Referenced by model_cube_write().
model_cube_write()
void model_cube_write (const char * filepath, const float length, const unsigned int divisions)
Definition at line 183 of file generator.cpp.
{
  const unsigned int nVertices = model_cube_nVertices (divisions);
  float points[3 * nVertices];
  model_cube_vertices (length, divisions, points);
  points_write (filepath, nVertices, points);
}
References model_cube_nVertices(), model_cube_vertices(), and points_write().
Referenced by main().