Solar System - demo scence: Groups
Groups
Operations
Functions
void operations_push_groups (tinyxml2::XMLElement *group, std::vector< float > *operations)
Detailed Description
Function Documentation
operations_push_groups()
void operations_push_groups (tinyxml2::XMLElement * group, std::vector< float > * operations)
Definition at line 176 of file parsing.cpp.
{
  operations->push_back (BEGIN_GROUP);
  // Inside "transform" tag there can be multiple transformations.
  tinyxml2::XMLElement *transforms = group->FirstChildElement ("transform");
  tinyxml2::XMLElement *models = group->FirstChildElement ("models");
  if (transforms)
    operations_push_transforms (transforms, operations);
  if (models)
    operations_push_models (models, operations);
  tinyxml2::XMLElement *childGroup = group->FirstChildElement ("group");
  if (childGroup)
    do
      operations_push_groups (childGroup, operations);
    while ((childGroup = childGroup->NextSiblingElement ("group")));
  operations->push_back (END_GROUP);
}
References BEGIN_GROUP, END_GROUP, operations_push_groups(), operations_push_models(), and operations_push_transforms().
Referenced by operations_load_xml(), and operations_push_groups().