Solar System - demo scence: Operations
Operations
Modules
Transforms
Models
Groups
Xml
Printing
Functions
void operations_render (std::vector< float > *operations)
Detailed Description
Data structure for Operations
⟨operations⟩ ::= ⟨position⟩⟨lookAt⟩⟨up⟩⟨projection⟩⟨grouping⟩⁺
     ⟨position⟩,⟨lookAt⟩,⟨up⟩,⟨projection⟩ ::= ⟨float⟩⟨float⟩⟨float⟩
⟨grouping⟩ ::= ⟨BEGIN_GROUP⟩⟨elem⟩⁺⟨END_GROUP⟩
⟨elem⟩ ::= ⟨transformation⟩ | ⟨model_loading⟩ | <grouping>
⟨transformation⟩ ::= ⟨translation⟩ | ⟨rotation⟩ | ⟨scaling⟩
⟨translation⟩ ::= ⟨simple_translation⟩ | ⟨extended_translation⟩
     ⟨simple_translation⟩ ::= ⟨TRANSLATE⟩⟨float⟩⟨float⟩⟨float⟩
     ⟨extended_translation⟩ ::= ⟨EXTENDED_TRANSLATE⟩⟨time⟩⟨align⟩⟨number_of_points⟩⟨vec3f⟩⁺
         ⟨time⟩  ::= ⟨float⟩
         ⟨align⟩ ::= ⟨bool⟩
         ⟨number_of_points⟩ ::= ⟨int⟩
⟨rotation⟩ ::= ⟨simple_rotation⟩ | ⟨extended_rotation⟩
     ⟨simple_rotation⟩ ::= ⟨ROTATE⟩⟨float⟩⟨float⟩⟨float⟩[angle]
         ⟨angle⟩ ::= ⟨float⟩
     ⟨extended_rotation⟩ ::= ⟨EXTENDED_ROTATE⟩⟨vec3f⟩
⟨scaling⟩ ::= ⟨SCALE⟩⟨float⟩⟨float⟩⟨float⟩
⟨model_loading⟩ ::= ⟨LOAD_MODEL⟩ ⟨number of characters⟩ ⟨char⟩⁺
     ⟨number of characters⟩ ::= <int>
⟨vec3f⟩ ::= ⟨float⟩⟨float⟩⟨float⟩
example of ⟨grouping⟩:
LOAD_MODEL 7 'e' 'x' 'a' 'm' 'p' 'l' 'e'
Note: we'll use an array of floats, therefore we will need to cast to char when reading the model filename characters and to int when reading the number of characters.
Function Documentation
operations_render()
void operations_render (std::vector< float > * operations)
Definition at line 317 of file engine.cpp.
{
  unsigned int i = 0;
  static bool hasPushedModels = false;
  static bool hasLoadedCurves = false;
  static vector<vector<vec3>> curves;
  DEFAULT_GLOBAL_EYE_X = operations->at (i);
  DEFAULT_GLOBAL_EYE_Y = operations->at (i + 1);
  DEFAULT_GLOBAL_EYE_Z = operations->at (i + 2);
  cartesian2Spherical (
      DEFAULT_GLOBAL_EYE_X, DEFAULT_GLOBAL_EYE_Y, DEFAULT_GLOBAL_EYE_Z,
      &DEFAULT_GLOBAL_RADIUS, &DEFAULT_GLOBAL_AZIMUTH, &DEFAULT_GLOBAL_ELEVATION);
  i += 3;
  DEFAULT_GLOBAL_CENTER_X = operations->at (i);
  DEFAULT_GLOBAL_CENTER_Y = operations->at (i + 1);
  DEFAULT_GLOBAL_CENTER_Z = operations->at (i + 2);
  i += 3;
  DEFAULT_GLOBAL_UP_X = operations->at (i);
  DEFAULT_GLOBAL_UP_Y = operations->at (i + 1);
  DEFAULT_GLOBAL_UP_Z = operations->at (i + 2);
  i += 3;
  DEFAULT_GLOBAL_FOV = operations->at (i);
  DEFAULT_GLOBAL_NEAR = operations->at (i + 1);
  DEFAULT_GLOBAL_FAR = operations->at (i + 2);
  unsigned int model_num = 0;
  for (i += 3; i < operations->size (); i++)
    {
      switch ((int) operations->at (i))
        {
          case ROTATE:
            glRotatef (operations->at (i + 1),
                       operations->at (i + 2),
                       operations->at (i + 3),
                       operations->at (i + 4));
          i += 4;
          continue;
          case EXTENDED_ROTATE:
            {
              advance_in_rotation (
                  operations->at (i + 1),
                  {
                      operations->at (i + 2),
                      operations->at (i + 3),
                      operations->at (i + 4)
                  });
              i += 4; //time, axis_of_rotation
              continue;
            }
          case TRANSLATE:
            glTranslatef (operations->at (i + 1),
                          operations->at (i + 2),
                          operations->at (i + 3));
          i += 3;
          continue;
          case EXTENDED_TRANSLATE:
            {
              int number_of_points = (int) operations->at (i + 3);
              vector<vec3> new_curve (number_of_points);
              if (!hasLoadedCurves)
                {
                  for (int j = 0; j < number_of_points; ++j)
                    {
                      int idx = 3*j;
                      new_curve.at (j)[0] = operations->at (i + 4 + idx);
                      new_curve.at (j)[1] = operations->at (i + 4 + idx + 1);
                      new_curve.at (j)[2] = operations->at (i + 4 + idx + 2);
                    }
                  curves.push_back (new_curve);
                }
              auto curve = curves.back ();
              renderCurve (Mcr, curve);
              advance_in_curve (
                  operations->at (i + 1),
                  (bool) operations->at (i + 2),
                  Mcr,
                  curves.back ());
              i += 3 + number_of_points * 3; // 3 - time,align,number_of_points,points...
              continue;
            }
          case SCALE:
            glScalef (operations->at (i + 1),
                      operations->at (i + 2),
                      operations->at (i + 3));
          i += 3;
          continue;
          case BEGIN_GROUP:
            glPushMatrix ();
          continue;
          case END_GROUP:
            glPopMatrix ();
          continue;
          case LOAD_MODEL:
            {
              int stringSize = (int) operations->at (i + 1);
              if (!hasPushedModels)
                {
                  char modelName[stringSize + 1];
                  int j;
                  for (j = 0; j < stringSize; j++)
                    modelName[j] = (char) operations->at (i + 2 + j);
                  modelName[j] = 0;
                  globalModels.push_back (allocModel (modelName));
                  glGenBuffers (1, &vbo_indices[model_num]);
                  glBindBuffer (GL_ARRAY_BUFFER, vbo_indices[model_num]);
                  Model m = globalModels.back ();
                  glBufferData (GL_ARRAY_BUFFER, sizeof (float) * 3 * m->nVertices, m->vertices, GL_STATIC_DRAW);
                  glBindBuffer (GL_ARRAY_BUFFER, 0); //unbind
                  free (m->vertices);
                }
              renderModel (globalModels[model_num], vbo_indices[model_num]);
              model_num++;
              i += stringSize + 1; //just to be explicit
              continue;
            }
        }
    }
  hasPushedModels = true;
  hasLoadedCurves = true;
}
References advance_in_curve(), advance_in_rotation(), allocModel(), BEGIN_GROUP, cartesian2Spherical(), DEFAULT_GLOBAL_AZIMUTH, DEFAULT_GLOBAL_CENTER_X, DEFAULT_GLOBAL_CENTER_Y, DEFAULT_GLOBAL_CENTER_Z, DEFAULT_GLOBAL_ELEVATION, DEFAULT_GLOBAL_EYE_X, DEFAULT_GLOBAL_EYE_Y, DEFAULT_GLOBAL_EYE_Z, DEFAULT_GLOBAL_FAR, DEFAULT_GLOBAL_FOV, DEFAULT_GLOBAL_NEAR, DEFAULT_GLOBAL_RADIUS, DEFAULT_GLOBAL_UP_X, DEFAULT_GLOBAL_UP_Y, DEFAULT_GLOBAL_UP_Z, END_GROUP, EXTENDED_ROTATE, EXTENDED_TRANSLATE, globalModels, LOAD_MODEL, Mcr, model::nVertices, renderCurve(), renderModel(), ROTATE, SCALE, TRANSLATE, vbo_indices(), and model::vertices.
Referenced by renderScene(), and xml_load_and_set_env().