Solar System - demo scence: Cone
Cone
Generator » Model
Functions
static void model_cone_vertex (const float r, const float height, const float theta, const float h, unsigned int *pos, float *points)
void model_cone_vertices (const float r, const float height, const unsigned int slices, const unsigned int stacks, float points[])
static unsigned int model_cone_nVertices (const unsigned int stacks, const unsigned int slices)
void model_cone_write (const char *filepath, const float radius, const float height, const unsigned int slices, const unsigned int stacks)
Detailed Description
Function Documentation
model_cone_nVertices()
static unsigned int model_cone_nVertices (const unsigned int stacks, const unsigned int slices) inline static
Definition at line 264 of file generator.cpp.
{
  return slices * stacks * 9;
}
Referenced by model_cone_write().
model_cone_vertex()
static void model_cone_vertex (const float r, const float height, const float theta, const float h, unsigned int * pos, float * points) inline static
\begin{aligned} x &= r⋅\frac{h}{\textrm{height}} ⋅ \cos(θ)\\[2em] y &= h + \textrm{height}\\[2em] z &= r⋅\frac{h}{\textrm{height}} ⋅ \sin(θ) \end{aligned}
\begin{aligned} r &≥ 0\\ θ &∈ \left\{-π + i⋅s : s = \frac{2π}{\textrm{slices}} ∧ i ∈ \{0,...,\textrm{slices}\} \right\}\\ h &∈ \left\{- \textrm{height} + j⋅t : t = \frac{\textrm{height}}{\textrm{stacks}} ∧ j ∈ \{0,...,\textrm{stacks}\} \right\} \end{aligned}
See the 3d model.
Definition at line 212 of file generator.cpp.
{
  /*
     x = r ⋅ (h/height) ⋅ cos(θ)
     y = 2 ⋅ (height + h)
     z = r ⋅ (h/height) ⋅ sin(θ)
     r ≥ 0
     θ ∈ {-π      + i⋅s : s = 2π/slices      ∧ i ∈ {0,...,slices} }
     h ∈ {-height + j⋅t : t =  height/stacks ∧ j ∈ {0,...,stacks} }
     check:
         1. https://www.math3d.org/7oeSkmuns
   */
  points_vertex (r * h / height * cos (theta), height + h, r * h / height * sin (theta), pos, points);
}
References points_vertex().
Referenced by model_cone_vertices().
model_cone_vertices()
void model_cone_vertices (const float r, const float height, const unsigned int slices, const unsigned int stacks, float points[])
Definition at line 230 of file generator.cpp.
{
  const float s = 2.0f * (float) M_PI / (float) slices;
  const float t = height / (float) stacks;
  const float theta = -M_PI;
  const float h = -height;
  unsigned int pos = 0;
  for (unsigned int m = 1; m <= slices; m++)
    {
      for (unsigned int n = 1; n <= stacks; n++)
        {
          float i = (float) m;
          float j = (float) n;
          //base
          points_vertex (0, 0, 0, &pos, points); //O
          model_cone_vertex (r, height, theta + s * (i - 1), h, &pos, points); //P1
          model_cone_vertex (r, height, theta + s * i, h, &pos, points); //P2
          model_cone_vertex (r, height, theta + s * i, h + t * (j - 1), &pos, points); // P2
          model_cone_vertex (r, height, theta + s * (i - 1), h + t * j, &pos, points); // P1'
          model_cone_vertex (r, height, theta + s * i, h + t * j, &pos, points); //P2'
          model_cone_vertex (r, height, theta + s * i, h + t * (j - 1), &pos, points); // P2
          model_cone_vertex (r, height, theta + s * (i - 1), h + t * (j - 1), &pos, points); // P1
          model_cone_vertex (r, height, theta + s * (i - 1), h + t * j, &pos, points); // P1'
        }
    }
}
References model_cone_vertex(), and points_vertex().
Referenced by model_cone_write().
model_cone_write()
void model_cone_write (const char * filepath, const float radius, const float height, const unsigned int slices, const unsigned int stacks)
Definition at line 269 of file generator.cpp.
{
  const unsigned int nVertices = model_cone_nVertices (stacks, slices);
  float points[3 * nVertices];
  model_cone_vertices (radius, height, slices, stacks, points);
  points_write (filepath, nVertices, points);
}
References model_cone_nVertices(), model_cone_vertices(), and points_write().
Referenced by main().