Solar System - demo scence: src/parsing.cpp File Reference
parsing.cpp File Reference
#include <vector>
#include <stdio.h>
#include <string.h>
#include "tinyxml2.h"
#include "parsing.h"
Functions
void operations_push_transform_attributes (tinyxml2::XMLElement *transform, std::vector< float > *operations)
void operations_push_extended_translate_attributes (tinyxml2::XMLElement *extended_translate, std::vector< float > *operations)
void operations_push_transformation (tinyxml2::XMLElement *transformation, std::vector< float > *operations)
void operations_push_transforms (tinyxml2::XMLElement *transforms, std::vector< float > *operations)
void operations_push_model (tinyxml2::XMLElement *model, std::vector< float > *operations)
void operations_push_models (tinyxml2::XMLElement *models, std::vector< float > *operations)
void operations_push_groups (tinyxml2::XMLElement *group, std::vector< float > *operations)
void operations_load_xml (const char *filename, std::vector< float > *operations)
void operations_print (std::vector< float > *operations)
void example1 (const char *filename)
int main2 (int argc, char *argv[])
Function Documentation
example1()
void example1 (const char * filename)
Definition at line 336 of file parsing.cpp.
{
  tinyxml2::XMLDocument doc;
  if (doc.LoadFile (filename))
    {
      fprintf (stderr, "%s", doc.ErrorName ());
      exit (1);
    }
  std::vector<float> operations;
  operations_load_xml (filename, &operations);
  operations_print (&operations);
}
References operations_load_xml(), and operations_print().
Referenced by main2().
main2()
int main2 (int argc, char * argv[])
Definition at line 351 of file parsing.cpp.
{
  example1 ("test_files_phase_2/test_2_3.xml");
  return 1;
}
References example1().